### ISSUE TITLE
Kanban Board for Final capstone API and Final Capstone UI

### ISSUE THREAD

**Issue by awaisanwar544** [awaisanwar544/final-capstone-api#18]
We are a team of 5 divided into FronEnd and BackEnd teams.

### Frontend Team:

1. @Kakalanp 
2. @awaisanwar544 

Link to frontend(UI) kanban board: https://github.com/awaisanwar544/final-capstone-ui/projects/1
![image](https://user-images.githubusercontent.com/10048317/177626342-04ddd58f-96b0-45ec-8631-a6561329347d.png)

### Backend Team:

1. @VicPeralta 
2. @ryxtor 
3. @John-Arboleda 

Link to backend(API) kanban board: https://github.com/awaisanwar544/final-capstone-api/projects/1
![image](https://user-images.githubusercontent.com/10048317/177626275-81f99eea-859e-43ec-bae3-a685991b78a8.png)

**Comment by MuriloRoque** [comment]
Hi @awaisanwar544, @VicPeralta, @ryxtor, @John-Arboleda, @Kakalanp,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
